### ISSUE TITLE
Project abandoned?

### ISSUE THREAD

**Issue by ghost** [0x666c/Minecraft-LWJGL-3#1]
I saw that the last commit was from 2019, so I am just asking if the project is abandoned.
If so, then you should set this project to like read only
But you are doing a great job on this project! :)

**Comment by jiftoo** [comment]
Project is totally abandoned, but until I'm 100% sure that I won't do any LWJGL stuff again in the future, I'll keep this repo as-is


(lazy)

**Comment by Apple26j** [comment]
So, I'm making Minecraft in LWJGL 3 (a recode just like you have done)
Right now, I'm focusing on the GUIs (still working on the main menu) because I want it to look exactly the same as Minecraft's
The only thing is since Minecraft has a lot of updates with so many features, the Minecraft recode will be on Minecraft 1.12.2
